fix: YAML file

diff --git a/.github/workflows/azure-static-web-apps-deploy.yml b/.github/workflows/azure-static-web-apps-deploy.yml
--- a/.github/workflows/azure-static-web-apps-deploy.yml
+++ b/.github/workflows/azure-static-web-apps-deploy.yml
@@ -18,6 +18,12 @@ jobs:
       - uses: actions/checkout@v3
         with:
           submodules: true
+      - name: List files for debugging
+        run: |
+          echo "Checking Root:"
+          ls -R
+          echo "Checking for requirements.txt in api folder:"
+          ls api/requirements.txt || echo "FILE NOT FOUND IN api/"
       
       - name: Build And Deploy
         id: builddeploy
